version: '3.9'

services:
  web-demo-1:
    build: .
    container_name: web-demo-1
    restart: always

  web-demo-2:
    build: .
    container_name: web-demo-2
    restart: always

  web-demo-3:
    build: .
    container_name: web-demo-3
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web-demo-1
      - web-demo-2
      - web-demo-3
    restart: always